version: '3'
services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9002:9002"
    depends_on:
      - w2_status_app1
      - w2_status_app2
      - w2_status_app3
      - w2_status_app4

  w2_status_app1:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
#      REDIS_URL: "redis://wepp.cloud:6379"  # wepp2
      REDIS_URL: "redis://172.17.0.1:6379"
    expose:
      - "9002"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_status_app2:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
#      REDIS_URL: "redis://wepp.cloud:6379"  # wepp2
      REDIS_URL: "redis://172.17.0.1:6379"
    expose:
      - "9002"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_status_app3:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
#      REDIS_URL: "redis://wepp.cloud:6379"  # wepp2
      REDIS_URL: "redis://172.17.0.1:6379"
    expose:
      - "9002"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_status_app4:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
#      REDIS_URL: "redis://wepp.cloud:6379"  # wepp2
      REDIS_URL: "redis://172.17.0.1:6379"
    expose:
      - "9002"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

