version: '3'
services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9001:9001"
    depends_on:
      - w2_preflight_app1
      - w2_preflight_app2
      - w2_preflight_app3
      - w2_preflight_app4

  w2_preflight_app1:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}  # Use environment variable
    expose:
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_preflight_app2:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}  # Use environment variable
    expose:
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_preflight_app3:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}  # Use environment variable
    expose:
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  w2_preflight_app4:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}  # Use environment variable
    expose:
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

