version: '3'
services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9001:9001"  # HAProxy will listen on port 80 of the host
    depends_on:
      - w2_preflight_app

  w2_preflight_app:
    build:
      context: ./  # Directory containing the Dockerfile and source code
      dockerfile: Dockerfile  # Only necessary if your Dockerfile has a different name
    environment:
#      REDIS_URL: "redis://wepp.cloud:6379"  # wepp2
      REDIS_URL: "redis://172.17.0.1:6379"  # wepp1
    expose:
      - "9001"  # Port the Tornado app listens on
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

